image_xscale = 22;
image_yscale = 6;
depth = -1;
timer = 50;
tempY = 600;
animSpeed =8;
goinDown = true;
chosen = false;
effectTimer = 20;
fadingTimer = -1;
goUp = false;
animDone = false;
text = "";
scale = 1;
selected = false;
targetScale = 1;
selectedTimer = -1;
tooltip = ""

goFadeTimer = 0;